name: 'Gitbook-Action'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'  # To Avoid Loop
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2

    # books/it
    - name: Gitbook Action
      uses: nianien/gitbook-action@master
      with:                                  
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: master
        source_dir: books/it
        publish_branch: gh-pages
        publish_dir: it

    # books/article
    - name: Gitbook Action
      uses: nianien/gitbook-action@master
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: master
        source_dir: books/article
        publish_branch: gh-pages
        publish_dir: article
        
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
   
