name: 'Gitbook-Action'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'  # To Avoid Loop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2

    # books/it
    - name: Gitbook Action
      uses: ZanderZhao/gitbook-action@master
      with:                                  
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: master
        source_dir: books/it
        publish_branch: gh-pages
        publish_dir: books/it

    # books/article
    - name: Gitbook Action
      uses: ZanderZhao/gitbook-action@master
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: master
        source_dir: books/article
        publish_branch: gh-pages
        publish_dir: books/article
