name: 'Gitbook-Action'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'  # To Avoid Loop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2

    # books/it
    - name: Gitbook Action
      uses: ZanderZhao/gitbook-action@master
      with:                                  
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: master
        source_dir: books/it
        publish_branch: gh-pages
        publish_dir: books/it
        publish_push_force: true

    # books/article
    - name: Gitbook Action
      uses: ZanderZhao/gitbook-action@master
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: master
        source_dir: books/article
        publish_branch: gh-pages
        publish_dir: books/article
        publish_push_force: true
    # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
