name: 'Gitbook Action Build'
on:
  push:
    branches:
      - master  # trigger branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v1
    - name: Gitbook Action
      uses: ZanderZhao/gitbook-action@v1.2.4
      with:                                       
        token: ${{ secrets.PERSONAL_TOKEN }}
